Feature/rla 3
Kevingg06/RefactorinLife5_app_final pull request #10
Opened 2024-06-05 15:13 UTC by Marynuccy

se crea la activity login junto a el diseño de su xml y la navegacion del prelogin hacia login

![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/167374572/d82760bd-511d-4d00-bd0b-a53df8347410)

![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/167374572/7406a932-b85b-4595-9040-22858cbac1c8)

2024-06-05 16:19 UTC, KevinMaggio requested changes

2024-06-05 16:19 UTC, KevinMaggio commented on app/build.gradle.kts
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/4555f287-b8c0-4825-8d27-33bf58209432)

No cambiar cosas agenas al Feature ( revertir estos cambios )

2024-06-05 16:19 UTC, KevinMaggio commented on app/src/main/java/com/example/myapplication/ui/prelogin/presenter/PreLoginActivity.kt
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/95ef2119-a5b7-4259-8fe9-b123a3e65f3c)

Es buena practica no llamar a las funciones nativas en el onCreate. 
vamos a tener varios onClick, crear funcion para integrarlos. 

fun actions() {
binding.buton1.setOnC.....

binding.buton2.seOnCli.....

binding.buton3.setOnCl...

}

2024-06-05 16:19 UTC, KevinMaggio commented on app/src/main/res/layout/activity_login.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/a5070d4d-020b-4c2a-a668-9ec0cfe4d2af)
no usar tamaño fijos para width. 
usar match_parent y achicar el width con margin

2024-06-05 16:19 UTC, KevinMaggio commented on app/src/main/res/layout/activity_login.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/3797d3a2-587e-4666-8f68-933e033ba04f)

no usar absoluteX

2024-06-05 16:19 UTC, KevinMaggio commented on app/src/main/res/layout/activity_login.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/e8805505-c69a-4106-a850-ecb96869349b)

por que se usa "ems " ( de no saber, sacarlo por favor )

2024-06-05 16:19 UTC, KevinMaggio commented on app/src/main/res/layout/activity_login.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/43d243ce-6837-4423-b269-0fb883e88e83)

sacar lineas muertas

2024-06-05 16:19 UTC, KevinMaggio commented on app/src/main/res/layout/activity_login.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/f3315653-149d-4e93-8ea6-921fc042192b)
para que se usa eltargetApi. ( de no justificar, borrarlo )

2024-06-05 16:19 UTC, KevinMaggio commented on app/src/main/res/layout/activity_login.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/298da302-733c-4a24-b2a0-81e0767eba33)

Sustraer los colores usados en el XML

2024-06-05 16:19 UTC, KevinMaggio commented on app/src/main/res/layout/activity_login.xml
Los ID en general no estan alineados. busquemos un patron con el equipo para seguir. 
EJ: 
pantalla_componente_uso
register_btn_back

2024-06-05 16:19 UTC, KevinMaggio commented on app/src/main/res/values/strings.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/4ca37c6f-fb32-4094-a6f1-cca6d87ad17f)

es una ensalada de ID. unificar un patron. 
pantalla_uso
register_title
register_email

2024-06-06 02:11 UTC, Kevingg06 commented on app/src/main/res/drawable/edit_text_stroke.xml
falta un salto de linea

2024-06-06 02:12 UTC, Kevingg06 commented on app/src/main/res/layout/activity_login.xml
falta salto de linea

2024-06-06 02:12 UTC, Kevingg06 commented on app/src/main/res/values/dimens.xml
falta salto de linea

2024-06-06 02:24 UTC, Kevingg06 approved these changes

2024-06-06 12:52 UTC, jhromeroabx approved these changes
Aprobado

2024-06-06 15:41 UTC, KevinMaggio requested changes

2024-06-06 15:41 UTC, KevinMaggio commented on app/src/main/res/values/strings.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/46149197-fc04-4a58-88ea-fa898dc05521)
el ID de este string esta en mayus " Login_btn"

2024-06-06 15:44 UTC, merged