Add view Register
Kevingg06/RefactorinLife5_app_final pull request #11
Opened 2024-06-05 17:20 UTC by M3fizN3rdi

Se realizo la vista de para la pantalla de Register

# Evidencia

![imagen](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/122237219/63ff17e1-1dca-4e18-8c25-7e128eb40e5f)

2024-06-05 19:12 UTC, KevinMaggio requested changes

2024-06-05 19:12 UTC, KevinMaggio commented on app/src/main/res/layout/activity_register.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/6a4a4b5b-99b1-4d57-b64e-657ba5198438)

unificar el formato de ID. 

pantalla_componente_uso

2024-06-05 19:12 UTC, KevinMaggio commented on app/src/main/res/layout/activity_register.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/1edd7b12-a3ef-45fa-80a2-6a33a32ee560)

no hace falta comentar cada componente

2024-06-05 19:12 UTC, KevinMaggio commented on app/src/main/res/layout/activity_register.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/ac15f168-5c40-4d75-bf78-12cc4a7a0ce1)

dejar un espacio entre componentes

2024-06-05 19:12 UTC, KevinMaggio commented on app/src/main/res/layout/activity_register.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/b635dd11-eb4f-4cbd-99c4-3a3cd292abfe)

Explicar el uso de ems. ( de no poder justificarlo, borrarlo )

2024-06-05 19:12 UTC, KevinMaggio commented on app/src/main/res/values/strings.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/86111731/3f896622-df56-455e-9f30-5b8a62ce992b)

refactorizar el sistema de ID

2024-06-06 02:29 UTC, Kevingg06 approved these changes

2024-06-06 03:35 UTC, Marynuccy commented on app/src/main/res/layout/activity_register.xml
![image](https://github.com/Kevingg06/RefactorinLife5_app_final/assets/167374572/ef2824c6-53d0-40ac-88b7-0a4b25316b91)

no uses en el with una cantidad de dp, pone match parent y ajusta con el margin

2024-06-06 04:12 UTC, Marynuccy approved these changes

2024-06-15 16:12 UTC, merged